import { useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import PortalLayout from '@/components/PortalLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ArrowLeft, Sparkles, CheckCircle2, AlertCircle, Plus, Trash2 } from 'lucide-react';

type Priority = 'P1' | 'P2' | 'P3' | 'OK';

interface Finding {
  id: string;
  section: string;
  priority: Priority;
  observation: string;
  recommendation: string;
  photos: string[]; // base64 or URLs
}

const SECTIONS = [
  'Roofing', 'Exterior', 'Foundation', 'Electrical',
  'Plumbing', 'HVAC', 'Insulation', 'Interior',
];

const PRIORITY_COLORS: Record<Priority, string> = {
  P1: 'bg-red-100 border-red-300 text-red-700',
  P2: 'bg-amber-100 border-amber-300 text-amber-700',
  P3: 'bg-blue-100 border-blue-300 text-blue-700',
  OK: 'bg-green-100 border-green-300 text-green-700',
};

const PRIORITY_LABELS: Record<Priority, string> = {
  P1: 'P1 — Safety / Urgent',
  P2: 'P2 — Major Defect',
  P3: 'P3 — Minor / Monitor',
  OK: 'OK — Satisfactory',
};

export default function ReportGeneratorPage() {
  const { id: jobId } = useParams<{ id: string }>();
  const navigate = useNavigate();

  // Step 1: property info
  const [address, setAddress] = useState('');
  const [clientEmail, setClientEmail] = useState('');
  const [inspectionType, setInspectionType] = useState('Pre-Purchase Home Inspection');
  const [inspectionDate, setInspectionDate] = useState('');
  const [inspector, setInspector] = useState('ASADS Certified Inspector');

  // Step 2: findings
  const [findings, setFindings] = useState<Finding[]>([
    { id: crypto.randomUUID(), section: 'Roofing', priority: 'OK', observation: '', recommendation: '', photos: [] },
  ]);

  // Step 3: generation
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [generating, setGenerating] = useState(false);
  const [generatedHtml, setGeneratedHtml] = useState('');
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState('');

  function addFinding() {
    setFindings(prev => [...prev, {
      id: crypto.randomUUID(),
      section: SECTIONS[0],
      priority: 'OK',
      observation: '',
      recommendation: '',
      photos: [],
    }]);
  }

  function removeFinding(id: string) {
    setFindings(prev => prev.filter(f => f.id !== id));
  }

  function updateFinding(id: string, patch: Partial<Finding>) {
    setFindings(prev => prev.map(f => f.id === id ? { ...f, ...patch } : f));
  }

  async function generateReport() {
    setError('');
    setGenerating(true);

    const prompt = buildScoutPrompt();

    try {
      // Call Claude via server-side proxy (Supabase Edge Function) to avoid exposing API key
      const { data, error: fnErr } = await supabase.functions.invoke('generate-report', {
        body: {
          prompt,
          address,
          clientEmail,
          inspectionType,
          inspectionDate,
          inspector,
          findings,
        },
      });

      if (fnErr || !data?.html) {
        setError(fnErr?.message ?? 'Report generation failed. Check that the Edge Function is deployed.');
        setGenerating(false);
        return;
      }

      setGeneratedHtml(data.html);
      setStep(3);
    } catch (err: unknown) {
      setError((err as Error).message);
    }
    setGenerating(false);
  }

  function buildScoutPrompt(): string {
    const findingsList = findings.map(f =>
      `[${f.section}] ${f.priority}: ${f.observation || '(no observation)'} | Rec: ${f.recommendation || 'N/A'}`
    ).join('\n');

    return `You are Scout, ASADS's AI report writer. Generate a professional home inspection report in HTML.

Property: ${address}
Client email: ${clientEmail}
Inspection type: ${inspectionType}
Date: ${inspectionDate}
Inspector: ${inspector}

FINDINGS:
${findingsList}

OUTPUT FORMAT:
Generate a complete self-contained HTML document styled with inline CSS. Include:
1. Cover page with ASADS branding (blue #1d4ed8), address, date, inspector name
2. Summary table: count of P1/P2/P3/OK findings per section
3. Finding cards for each finding:
   - Badge coloured by priority (P1=red, P2=amber, P3=blue, OK=green)
   - Section heading, observation paragraph, recommendation paragraph
4. Footer: "Report generated by Scout AI · ASADS Home Inspection · asads.ca · (647) 801-9311"

Priority meanings:
- P1: Safety hazard — requires immediate attention
- P2: Major defect — repair before closing
- P3: Minor issue — monitor or address when convenient
- OK: Satisfactory condition

Write professional, clear language. Every finding card must reference the specific section. Do NOT use placeholder text — use the actual findings provided. Return ONLY the HTML, no markdown.`;
  }

  async function saveReport() {
    setSaving(true);
    setError('');

    // Determine job_id: either from URL param or find by address+clientEmail
    let targetJobId = jobId;

    if (!targetJobId) {
      // Find the job
      const { data: userData } = await supabase
        .from('users').select('id').eq('email', clientEmail).single();
      if (userData) {
        const { data: jobData } = await supabase
          .from('jobs').select('id').eq('homeowner_id', userData.id)
          .eq('address', address).single();
        targetJobId = jobData?.id;
      }
    }

    if (!targetJobId) {
      setError('Could not find matching job. Create the job first via Admin → New Job.');
      setSaving(false);
      return;
    }

    // Upload HTML to Supabase Storage
    const fileName = `report-${targetJobId}-${Date.now()}.html`;
    const blob = new Blob([generatedHtml], { type: 'text/html' });

    const { error: uploadErr } = await supabase.storage
      .from('reports')
      .upload(fileName, blob, { contentType: 'text/html', upsert: true });

    if (uploadErr) {
      setError('Upload failed: ' + uploadErr.message);
      setSaving(false);
      return;
    }

    const { data: { publicUrl } } = supabase.storage.from('reports').getPublicUrl(fileName);

    // Save report record
    await supabase.from('reports').insert({
      job_id: targetJobId,
      storage_url: publicUrl,
    });

    // Update job status to completed
    await supabase.from('jobs').update({
      status: 'completed',
      completed_at: new Date().toISOString(),
    }).eq('id', targetJobId);

    // Seed P1/P2 findings as maintenance checklist items
    const { data: userData2 } = await supabase
      .from('jobs').select('homeowner_id').eq('id', targetJobId).single();
    if (userData2) {
      const maintenanceItems = findings
        .filter(f => f.priority === 'P1' || f.priority === 'P2')
        .map(f => ({
          user_id: userData2.homeowner_id,
          title: f.observation || `${f.section} — ${f.priority} issue`,
          category: f.section,
          due_date: null,
          completed: false,
          property_address: address,
        }));
      if (maintenanceItems.length > 0) {
        await supabase.from('maintenance').insert(maintenanceItems);
      }
    }

    setSaving(false);
    setSaved(true);
    setTimeout(() => navigate('/admin'), 2000);
  }

  return (
    <PortalLayout>
      <div className="mb-6">
        <Button asChild variant="ghost" size="sm">
          <Link to="/admin" className="flex items-center gap-2 text-gray-600">
            <ArrowLeft className="h-4 w-4" />
            Back to Dashboard
          </Link>
        </Button>
      </div>

      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Scout AI Report Generator</h1>
          <p className="text-gray-500">Generate a professional inspection report with Claude AI</p>
        </div>
        {/* Step indicator */}
        <div className="hidden sm:flex items-center gap-2 text-sm">
          {(['1 Property', '2 Findings', '3 Review'] as const).map((label, i) => (
            <span key={label} className={`px-3 py-1 rounded-full font-medium ${
              step === i + 1 ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-500'
            }`}>{label}</span>
          ))}
        </div>
      </div>

      {error && (
        <div className="flex items-center gap-2 bg-red-50 border border-red-200 text-red-700 rounded-lg px-4 py-3 mb-6 text-sm">
          <AlertCircle className="h-4 w-4 shrink-0" />
          {error}
        </div>
      )}

      {/* ── STEP 1: Property Info ── */}
      {step === 1 && (
        <div className="bg-white border border-gray-200 rounded-xl p-8 max-w-xl">
          <h2 className="font-semibold text-gray-900 mb-5">Step 1 — Property Information</h2>
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label>Property address</Label>
              <Input value={address} onChange={e => setAddress(e.target.value)} placeholder="20 Fireside Dr, Barrie, ON" />
            </div>
            <div className="space-y-1.5">
              <Label>Client email</Label>
              <Input type="email" value={clientEmail} onChange={e => setClientEmail(e.target.value)} placeholder="client@example.com" />
            </div>
            <div className="space-y-1.5">
              <Label>Inspection type</Label>
              <Input value={inspectionType} onChange={e => setInspectionType(e.target.value)} />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label>Date of inspection</Label>
                <Input type="date" value={inspectionDate} onChange={e => setInspectionDate(e.target.value)} />
              </div>
              <div className="space-y-1.5">
                <Label>Inspector name</Label>
                <Input value={inspector} onChange={e => setInspector(e.target.value)} />
              </div>
            </div>
          </div>
          <Button
            className="mt-6 bg-blue-600 hover:bg-blue-700"
            onClick={() => setStep(2)}
            disabled={!address || !clientEmail}
          >
            Next: Enter Findings →
          </Button>
        </div>
      )}

      {/* ── STEP 2: Findings ── */}
      {step === 2 && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="font-semibold text-gray-900">Step 2 — Inspection Findings</h2>
            <Button size="sm" variant="outline" onClick={addFinding}>
              <Plus className="h-4 w-4 mr-1" />
              Add Finding
            </Button>
          </div>

          {findings.map(f => (
            <div key={f.id} className={`border rounded-xl p-5 ${PRIORITY_COLORS[f.priority]}`}>
              <div className="flex items-center gap-3 mb-4 flex-wrap">
                <select
                  className="bg-white border border-gray-300 rounded-md px-3 py-1.5 text-sm"
                  value={f.section}
                  onChange={e => updateFinding(f.id, { section: e.target.value })}
                >
                  {SECTIONS.map(s => <option key={s}>{s}</option>)}
                </select>
                <select
                  className="bg-white border border-gray-300 rounded-md px-3 py-1.5 text-sm font-medium"
                  value={f.priority}
                  onChange={e => updateFinding(f.id, { priority: e.target.value as Priority })}
                >
                  {(Object.entries(PRIORITY_LABELS) as [Priority, string][]).map(([k, v]) => (
                    <option key={k} value={k}>{v}</option>
                  ))}
                </select>
                <button
                  onClick={() => removeFinding(f.id)}
                  className="ml-auto text-gray-400 hover:text-red-500"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
              <div className="space-y-3">
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">Observation</label>
                  <textarea
                    className="w-full bg-white border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                    rows={2}
                    placeholder="Describe what was observed…"
                    value={f.observation}
                    onChange={e => updateFinding(f.id, { observation: e.target.value })}
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">Recommendation</label>
                  <textarea
                    className="w-full bg-white border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                    rows={2}
                    placeholder="What should the homeowner do?"
                    value={f.recommendation}
                    onChange={e => updateFinding(f.id, { recommendation: e.target.value })}
                  />
                </div>
              </div>
            </div>
          ))}

          <div className="flex gap-3 pt-2">
            <Button variant="outline" onClick={() => setStep(1)}>← Back</Button>
            <Button
              className="bg-blue-600 hover:bg-blue-700 flex items-center gap-2"
              onClick={generateReport}
              disabled={generating || findings.length === 0}
            >
              <Sparkles className="h-4 w-4" />
              {generating ? 'Generating with Scout…' : 'Generate with Scout AI'}
            </Button>
          </div>
        </div>
      )}

      {/* ── STEP 3: Review & Save ── */}
      {step === 3 && (
        <div className="space-y-6">
          <h2 className="font-semibold text-gray-900">Step 3 — Review & Save Report</h2>

          {saved ? (
            <div className="flex flex-col items-center gap-3 py-12 text-center bg-white border border-gray-200 rounded-xl">
              <CheckCircle2 className="h-12 w-12 text-green-500" />
              <p className="font-semibold text-gray-900">Report saved & client notified!</p>
              <p className="text-sm text-gray-500">Returning to admin dashboard…</p>
            </div>
          ) : (
            <>
              {/* Preview */}
              <div className="bg-white border border-gray-200 rounded-xl overflow-hidden">
                <div
                  className="w-full max-h-[600px] overflow-auto p-4"
                  dangerouslySetInnerHTML={{ __html: generatedHtml }}
                />
              </div>

              <div className="flex gap-3">
                <Button variant="outline" onClick={() => setStep(2)}>← Revise Findings</Button>
                <Button
                  className="bg-green-600 hover:bg-green-700 flex items-center gap-2"
                  onClick={saveReport}
                  disabled={saving}
                >
                  <CheckCircle2 className="h-4 w-4" />
                  {saving ? 'Saving…' : 'Save & Send to Client'}
                </Button>
              </div>
            </>
          )}
        </div>
      )}
    </PortalLayout>
  );
}
